version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker CLI
          command: apk update && apk add docker
      - run:
          name: Build Webserver Image
          command: docker build -t api:latest .
      - run:
          name: Save Image
          command: mkdir -p workspace && docker save api:latest > workspace/api.tar
      - persist_to_workspace:
          root: workspace
          paths:
            - api.tar
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest -W ignore::DeprecationWarning
      - run:
          name: Check coverage
          command: |
            coverage run src/*.py
            coverage report
            codecov
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Authenticate to Google Cloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Connect Docker and Google Cloud
          command: gcloud auth configure-docker
      - run:
          name: Push Docker image to GCR
          command: |
            docker load -i /tmp/workspace/api.tar
            if [ "$CIRCLE_BRANCH" == "master" ]
            then
                export IMAGE_TAG="latest"
            else
                export IMAGE_TAG=$CIRCLE_BRANCH
            fi
            docker tag api:latest us.gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:$IMAGE_TAG
            docker push us.gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:$IMAGE_TAG


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: -timmmmmm
      - test:
          filters:
            branches:
              ignore: -timmmmmm
      - deploy:
          filters:
            branches:
              ignore: -timmmmmm
          #requires:
          # - build
          # - test
    
